export const locales = {
  en: {
    lang: 'en', ogLocale: 'en_US',
    title: 'INFLORY — Monthly Instagram follower plans, at your pace',
    description: 'A little, throughout the month. Explore proposed Instagram follower subscriptions distributed over 30 days, from $19 USD/month. Register your interest before launch. No payment required.',
    skip: 'Skip to content', home: 'INFLORY home', navigation: 'Main navigation', language: 'Language',
    nav: ['Plans', 'How it works', 'I’m interested'],
    hero: ['Influence,', 'in rhythm.'],
    heroDescription: ['A little, throughout the month.', 'Instagram follower plans, distributed over 30 days.'],
    heroCta: 'Find your monthly rhythm', heroNote: 'A pre-launch concept. Explore now, with no payment.',
    calendar: ['Small steps.', 'A whole month.'], calendarLabel: 'A concept calendar illustrating distribution over 30 days, not actual results.', calendarLegend: 'A little, along the way', calendarNote: 'Illustrative schedule. Not delivery history or results.',
    strip: 'A rhythm for your presence.', plansTitle: ['A month that fits', 'where you are.'],
    plansNote: ['Proposed Instagram plans', 'Distributed over 30 days, across every plan.'],
    captions: ['A small beginning', 'A steady rhythm', 'A wider presence'], summaries: ['An opening pace for a new account.', 'A pace to keep moving with.', 'A little more room for the month.'],
    quantitySuffix: 'followers / 30 days', monthSuffix: '/ month',
    benefits: ['Proposed 30-day distribution', 'For one Instagram account', 'No account password required', 'Refill option under consideration'],
    planCta: 'I’m interested in {plan}',
    pricingNote: 'All prices in USD. Proposed prices and quantities, subject to change. Tax treatment will be confirmed at launch. No orders or payments are being accepted.',
    howTitle: ['A simple way', 'to think about it.'], plannedLabel: 'Proposed experience after launch',
    steps: [['Choose your pace', 'Pick a monthly plan', 'that suits your account.'], ['Across 30 days', 'Spread the delivery', 'throughout the month.'], ['Keep your rhythm', 'A subscription for the months', 'you choose to continue.']],
    faqTitle: ['A few things', 'to know first.'],
    faq: [
      ['Does signing up start the service?', 'Not yet. This is a pre-launch interest survey. We are not delivering followers, taking payments, or activating subscriptions. Interest registration does not collect contact details or add you to an email waitlist.'],
      ['Are these organically acquired followers?', 'We are evaluating a subscription using followers supplied by third parties. Distributing delivery over 30 days does not make it organic. Genuine interest, engagement, revenue, retention, and account safety are not guaranteed. This model may conflict with platform terms and result in account restrictions; launch remains under review.'],
      ['Will lost followers be replaced?', 'Followers may drop, and retained quantities are not guaranteed. This survey asks whether a refill option matters to you. Its scope, duration, and terms would be defined only after we verify supplier quality and costs.'],
      ['What about other social platforms?', 'The proposed prices and quantities are for Instagram. You can select YouTube or TikTok in the interest form to express demand for future support. Pricing and availability for those platforms are not promised.']
    ],
    closing: ['Your next month.', 'A little more intentional.'], closingCta: 'Leave a little interest', closingNote: 'About 10 seconds · No email · No payment',
    disclosure: 'INFLORY is researching a third-party supplied follower subscription. Scheduled delivery is not organic growth. Engagement, revenue, retention, account safety, and compliance with platform terms are not guaranteed.',
    privacyLink: 'Privacy & analytics', settings: 'Analytics settings', noScript: 'You can browse all plans. Enable JavaScript to register interest.', close: 'Close',
    formTitle: ['What does your', 'next month look like?'], formIntro: ['Tell us which plan interests you.', 'A pre-launch survey, without contact details.'],
    planLegend: 'Interested in', formPrice: '${price}/month · {followers} followers', platformLabel: 'Preferred platform', platformOptions: ['Instagram', 'YouTube (future interest)', 'TikTok (future interest)'],
    refill: 'A refill option would matter to me.', consent: 'I agree to Google Analytics collecting my plan and platform preferences and usage analytics.', more: 'Details', formSubmit: 'Register my interest',
    formFine: 'These plans consider third-party supplied followers, not guaranteed organic growth or retention. This is not a purchase or an email waitlist.',
    successTitle: ['Thanks for', 'the signal.'], successDetail: '{plan} · {platform}', successText: ['Your preference helps inform the concept.', 'No payment or subscription has started.'], successButton: 'Back to the plans',
    privacyTitle: 'Privacy & analytics', operator: 'Operator: The Mercenary · Concept: INFLORY',
    privacy: [
      ['What information is used?', 'We do not ask for your email, phone number, social account name, or password. With your consent, Google Analytics 4 processes page views, clicks, selected plan, platform, refill preference, device information and traffic-source data.'],
      ['Why is it used?', 'We compare visits, plan selection and expressed interest to understand demand. Interest registration does not store contact details or subscribe you to launch notifications.'],
      ['Your choices and retention', 'Analytics starts only after consent. You can withdraw it through Analytics settings in the footer. Your preference is saved in this browser. Analytics cookies and events follow the connected GA4 property’s retention settings and Google policies. Withdrawal stops future analytics on this page and attempts to remove its analytics cookies.']
    ], googlePrivacy: 'Google Privacy Policy', confirm: 'Done',
    consentTitle: 'Help shape the next month.', consentText: 'May we collect page-usage analytics?', deny: 'No thanks', allow: 'Allow analytics',
    ui: { pending: 'Interest registration is not open yet. Please check back soon.', sending: 'Sending your preference…', error: 'The connection did not complete. Please try again later or check your content blocker.', duplicate: 'You have already expressed interest in this session. Thank you.', consentRequired: 'Please agree to preference measurement to send this preference response.', selectPlan: 'Please choose a plan.', noAnalytics: 'Analytics is not active yet.', invalid: 'Please check your selections.' }
  },
  ko: {
    lang: 'ko', ogLocale: 'ko_KR',
    title: '인플로리 INFLORY — 인스타그램 팔로워 월 구독 사전 관심등록',
    description: '영향력에도 꾸준한 리듬이 필요하니까. 30일에 나누어 제공하는 인스타그램 팔로워 월 구독을 준비합니다. 월 $19 USD부터의 출시 검토안을 살펴보고 결제 없이 관심을 남겨주세요.',
    skip: '본문으로 바로가기', home: '인플로리 홈', navigation: '주요 메뉴', language: '언어', nav: ['플랜', '이용 방식', '관심 남기기'],
    hero: ['영향력을,', '꾸준히.'], heroDescription: ['한 번의 급증보다, 한 달의 리듬.', '30일에 나누어 이어가는 인스타그램 팔로워 플랜.'], heroCta: '내 플랜 먼저 살펴보기', heroNote: '출시 전 제안 · 지금은 결제 없이 관심만 남겨주세요.',
    calendar: ['작은 흐름이', '이어지는 한 달.'], calendarLabel: '30일 분산 제공 방식의 예시 달력. 실제 제공 실적이 아닙니다.', calendarLegend: '한 달에 나누는 방식', calendarNote: '제공 방식 예시 · 실제 일정 및 실적이 아닙니다.', strip: '지속하는 영향력의 시작.',
    plansTitle: ['지금의 나에게 맞는', '한 달을 고르세요.'], plansNote: ['인스타그램 기준 · 월 구독 제안', '모든 플랜은 30일 분산 제공을 검토합니다.'],
    captions: ['작은 시작', '꾸준한 리듬', '더 넓은 존재감'], summaries: ['새로운 계정의 첫 페이스.', '계속 이어가는 나만의 페이스.', '조금 더 크게 잡는 한 달.'], quantitySuffix: '명 / 30일', monthSuffix: '/ 월',
    benefits: ['30일에 나누어 제공하는 안', '인스타그램 계정 1개 기준', '계정 비밀번호 입력 없음', '이탈 보충 옵션은 수요 확인 중'], planCta: '{plan}에 관심 있어요',
    pricingNote: '모든 가격은 USD 기준 출시 검토안입니다. 가격·수량·세금 적용은 출시 시 확정하며, 현재 주문이나 결제를 받지 않습니다.', howTitle: ['생각하는 방식은', '단순합니다.'], plannedLabel: '출시 후 이용 방식 제안',
    steps: [['나의 플랜을 고르고', '지금의 계정에 맞는', '월 수량을 선택합니다.'], ['30일에 나누어', '한 번에 몰아넣는 대신', '한 달에 걸쳐 분산합니다.'], ['다음 달의 페이스로', '필요한 기간만 이어가는', '구독 방식을 준비합니다.']],
    faqTitle: ['궁금한 점,', '먼저 답할게요.'],
    faq: [
      ['지금 신청하면 바로 시작되나요?', '아직 출시 전입니다. 어떤 플랜에 관심이 있는지 확인하는 단계이며, 실제 팔로워 제공·결제·자동 갱신은 진행하지 않습니다. 관심등록은 이메일을 받지 않는 선호도 조사입니다.'],
      ['자연 유입 팔로워인가요?', '제3자 공급 방식의 팔로워 구독을 검토하는 서비스입니다. 30일 분산 제공은 자연 유입을 뜻하지 않으며, 실제 관심·참여·매출이나 계정 안전을 보장하지 않습니다. 플랫폼 이용약관에 저촉되거나 계정이 제한될 수 있어 출시 여부를 검토 중입니다.'],
      ['팔로워가 이탈하면 보충되나요?', '이탈 가능성이 있으며 유지 수량을 보장하지 않습니다. 보충 옵션의 필요성을 이번 조사에서 확인합니다. 공급 품질과 비용을 검증한 뒤 적용 범위·기간·조건을 안내할 예정입니다.'],
      ['다른 SNS도 사용할 수 있나요?', '현재 제안한 가격과 수량은 인스타그램 기준입니다. 관심등록에서 유튜브 또는 틱톡을 선택하면 향후 지원 수요로 참고합니다. 해당 채널의 가격이나 제공을 약속하는 것은 아닙니다.']
    ],
    closing: ['다음 한 달의', '영향력을 생각한다면.'], closingCta: '내 관심 플랜 남기기', closingNote: '약 10초 · 이메일 입력 없음 · 결제 없음',
    disclosure: 'INFLORY는 제3자 공급 방식의 팔로워 구독을 검토하는 사전 수요조사입니다. 분산 제공은 자연 유입이 아니며, 실제 참여·매출·유지 수량·계정 안전 및 플랫폼 정책 준수를 보장하지 않습니다.',
    privacyLink: '개인정보 및 통계 안내', settings: '통계 설정', noScript: '플랜을 살펴볼 수 있습니다. 관심등록은 JavaScript를 켠 브라우저에서 이용해주세요.', close: '닫기',
    formTitle: ['어떤 한 달을', '기대하시나요?'], formIntro: ['관심 있는 플랜을 알려주세요.', '연락처를 받지 않는 출시 전 선호도 조사입니다.'], planLegend: '관심 플랜', formPrice: '월 ${price} · {followers}명', platformLabel: '관심 채널', platformOptions: ['인스타그램', '유튜브 (지원 수요조사)', '틱톡 (지원 수요조사)'],
    refill: '이탈 보충 옵션이 있으면 좋겠어요.', consent: '선택한 플랜·채널과 이용 통계를 Google Analytics로 수집하는 데 동의합니다.', more: '자세히', formSubmit: '이 플랜에 관심 있어요',
    formFine: '팔로워는 제3자 공급 방식의 검토안이며 자연 유입·유지가 보장되지 않습니다. 구매나 대기자 연락처 등록이 아닙니다.',
    successTitle: ['관심을 표시해', '주셔서 감사합니다.'], successDetail: '{plan} · {platform}', successText: ['선택한 플랜을 서비스 검토에 참고합니다.', '결제나 구독이 시작되지는 않습니다.'], successButton: '플랜으로 돌아가기',
    privacyTitle: '개인정보 및 통계 안내', operator: '운영: The Mercenary · 서비스 기획명: INFLORY',
    privacy: [
      ['어떤 정보를 사용하나요?', '이메일, 전화번호, SNS 계정명·비밀번호를 받지 않습니다. 동의한 경우 Google Analytics 4를 통해 페이지 조회, 버튼 클릭, 선택한 플랜·채널·보충 옵션과 기기·유입 경로 등 이용 통계를 처리합니다.'],
      ['왜 사용하나요?', '방문 대비 플랜 선택과 관심등록 비율을 비교해 서비스 수요를 판단합니다. 관심등록은 연락처를 저장하는 대기자 명단이 아니며, 출시 알림을 보내지 않습니다.'],
      ['선택과 보관', '통계 수집은 동의 전 시작하지 않습니다. 페이지 하단의 통계 설정에서 거부로 변경할 수 있습니다. 선택 기록은 이 브라우저에 저장되며, Google Analytics의 쿠키·이벤트 보관은 연결된 속성 설정과 Google 정책을 따릅니다. 동의를 철회하면 이 페이지의 통계 전송을 중지하고 관련 분석 쿠키 삭제를 시도합니다.']
    ], googlePrivacy: 'Google 개인정보처리방침', confirm: '확인', consentTitle: '더 나은 한 달을 준비하도록.', consentText: '페이지 이용 통계 수집에 동의하시겠어요?', deny: '괜찮아요', allow: '동의할게요',
    ui: { pending: '관심등록은 아직 준비 중입니다. 곧 다시 찾아주세요.', sending: '관심을 전달하고 있어요…', error: '연결을 완료하지 못했습니다. 잠시 후 다시 시도하거나 콘텐츠 차단 설정을 확인해주세요.', duplicate: '이번 방문에서 이미 관심을 표시하셨습니다. 감사합니다.', consentRequired: '관심 응답을 보내려면 통계 수집에 동의해주세요.', selectPlan: '관심 플랜을 선택해주세요.', noAnalytics: '아직 이용 통계가 연결되지 않았습니다.', invalid: '선택한 항목을 확인해주세요.' }
  },
  ja: {
    lang: 'ja', ogLocale: 'ja_JP', title: 'INFLORY — Instagramフォロワーの月額プラン・事前関心登録',
    description: '影響力に、自分らしいリズムを。30日間に分けて提供するInstagramフォロワーの月額プランを検討しています。月額19米ドルからのプランに、支払いなしで関心をお寄せください。',
    skip: '本文へ移動', home: 'INFLORY ホーム', navigation: 'メインナビゲーション', language: '言語', nav: ['プラン', '仕組み', '関心を登録'],
    hero: ['影響力に、', 'リズムを。'], heroDescription: ['一度に増やすより、ひと月のペースで。', '30日間に分けて届けるInstagramフォロワープラン。'], heroCta: '自分のプランを見つける', heroNote: '公開前のサービス案です。今はお支払い不要。',
    calendar: ['小さな流れを、', 'ひと月つなぐ。'], calendarLabel: '30日間に分散して提供するイメージです。実際の実績ではありません。', calendarLegend: 'ひと月に分けて', calendarNote: '提供方法のイメージ。実際の日程・実績ではありません。', strip: '存在感を、少しずつ。',
    plansTitle: ['今の自分に合う、', 'ひと月を選ぼう。'], plansNote: ['Instagram向けの月額プラン案', 'すべて30日間の分散提供を検討しています。'],
    captions: ['小さなスタート', '続けるリズム', '広がる存在感'], summaries: ['新しいアカウントの第一歩に。', '自分のペースを続けたい方に。', 'ひと月を、少し大きく描く。'], quantitySuffix: '人 / 30日間', monthSuffix: '/ 月',
    benefits: ['30日間に分ける提供案', 'Instagramアカウント1件', 'アカウントのパスワード不要', '減少時の補充オプションを検討中'], planCta: '{plan}に興味があります',
    pricingNote: '価格は米ドル表示の検討案です。価格・人数・税の扱いは正式公開時に確定します。現在、注文や決済は受け付けていません。', howTitle: ['考えている仕組みは、', 'シンプルです。'], plannedLabel: '正式公開後の利用イメージ',
    steps: [['ペースを選ぶ', '今のアカウントに合う', '月間人数を選択。'], ['30日間に分ける', '一度にまとめず、', 'ひと月を通して分散。'], ['次のひと月へ', '必要な期間だけ続ける', 'サブスクを検討中。']],
    faqTitle: ['気になることを、', '先に。'],
    faq: [
      ['登録すると、すぐに始まりますか？', 'まだ公開前です。今回はプランへの関心を確認する調査で、フォロワー提供・決済・自動更新は行いません。メールアドレスを集めるウェイトリストではありません。'],
      ['自然に獲得したフォロワーですか？', '第三者から供給されるフォロワーを利用したプランを検討しています。30日間に分けても自然流入になるわけではありません。実際の関心・反応・売上・定着・アカウントの安全は保証しません。プラットフォーム規約に抵触し、アカウント制限につながる可能性があるため、公開の可否を検討中です。'],
      ['減ったフォロワーは補充されますか？', 'フォロワーは減少する場合があり、維持人数は保証しません。今回の調査では補充オプションへの需要を確認します。供給品質と費用を検証した後、対象・期間・条件を決める予定です。'],
      ['他のSNSにも対応しますか？', '提示した価格と人数はInstagram向けです。関心登録でYouTubeやTikTokを選ぶと、今後の対応を検討する参考になります。価格や提供を約束するものではありません。']
    ],
    closing: ['次のひと月を、', '自分らしいペースで。'], closingCta: '気になるプランを伝える', closingNote: '約10秒 · メール不要 · 決済なし',
    disclosure: 'INFLORYは第三者供給によるフォロワーの月額プランを検討する事前調査です。分散提供は自然な成長ではありません。反応・売上・維持人数・安全性・プラットフォーム規約への適合は保証しません。',
    privacyLink: 'プライバシー・計測', settings: '計測設定', noScript: 'すべてのプランをご覧いただけます。関心登録にはJavaScriptを有効にしてください。', close: '閉じる',
    formTitle: ['どんなひと月を、', '思い描きますか？'], formIntro: ['気になるプランを教えてください。', '連絡先を集めない事前調査です。'], planLegend: '関心のあるプラン', formPrice: '月額${price} · {followers}人', platformLabel: '関心のあるSNS', platformOptions: ['Instagram', 'YouTube（今後の需要調査）', 'TikTok（今後の需要調査）'],
    refill: '減少時の補充オプションに関心があります。', consent: '選択したプラン・SNSと利用統計をGoogle Analyticsで収集することに同意します。', more: '詳細', formSubmit: 'このプランへの関心を登録',
    formFine: '第三者供給の検討案です。自然流入や定着は保証されません。購入・メール待機リスト登録ではありません。',
    successTitle: ['関心をお寄せいただき、', 'ありがとうございます。'], successDetail: '{plan} · {platform}', successText: ['サービスの検討に参考とさせていただきます。', '決済やサブスクは開始されません。'], successButton: 'プランに戻る',
    privacyTitle: 'プライバシー・計測', operator: '運営：The Mercenary · サービス案：INFLORY',
    privacy: [
      ['何を収集しますか？', 'メール・電話番号・SNSアカウント名・パスワードは収集しません。同意した場合に限り、Google Analytics 4で閲覧・クリック・選択プラン・SNS・補充の希望・端末・流入経路などを処理します。'],
      ['何のために使いますか？', '閲覧数に対するプラン選択・関心登録の割合から需要を検証します。連絡先は保存せず、公開通知も送信しません。'],
      ['選択と保存', '同意前は計測を開始しません。フッターの計測設定で撤回できます。選択はこのブラウザに保存されます。分析用Cookieとイベントの保存期間は接続先GA4とGoogleの規定に従います。撤回後は送信を停止し、このページの分析用Cookieの削除を試みます。']
    ], googlePrivacy: 'Google プライバシーポリシー', confirm: '確認', consentTitle: '次のひと月のために。', consentText: 'ページの利用統計を収集してもよろしいですか？', deny: '許可しない', allow: '許可する',
    ui: { pending: '関心登録は準備中です。しばらくしてからお越しください。', sending: '送信しています…', error: '接続できませんでした。後で再試行するか、コンテンツブロック設定をご確認ください。', duplicate: '今回の訪問では、すでに関心を登録しています。ありがとうございます。', consentRequired: '回答の送信には計測への同意が必要です。', selectPlan: 'プランを選んでください。', noAnalytics: '計測はまだ接続されていません。', invalid: '選択内容を確認してください。' }
  },
  'zh-hans': {
    lang: 'zh-Hans', ogLocale: 'zh_CN', title: 'INFLORY — Instagram 粉丝月度订阅方案 · 上线前意向登记',
    description: '让影响力，持续发生。探索按30天分批提供的Instagram粉丝月度订阅方案，拟定价格每月19美元起。上线前表达意向，无需付款。',
    skip: '跳转至正文', home: 'INFLORY 首页', navigation: '主导航', language: '语言', nav: ['订阅方案', '服务方式', '表达意向'],
    hero: ['让影响力，', '持续发生。'], heroDescription: ['比起一次激增，更看重一整月的节奏。', '按30天分批提供的 Instagram 粉丝方案。'], heroCta: '找到适合我的月度方案', heroNote: '上线前的服务构想。现在仅登记意向，无需付款。',
    calendar: ['点滴汇聚，', '贯穿一整月。'], calendarLabel: '30天分批提供方式的示意日历，并非实际服务记录。', calendarLegend: '分散在一个月里', calendarNote: '仅为方式示意，并非实际时间表或成果。', strip: '让存在感，拥有节奏。',
    plansTitle: ['选择适合当下的', '月度节奏。'], plansNote: ['Instagram 月度订阅拟定方案', '所有方案均考虑按30天分批提供。'],
    captions: ['轻盈起步', '稳定节奏', '更广存在感'], summaries: ['为新账号迈出第一步。', '以自己的节奏持续前行。', '为下一个月留出更多空间。'], quantitySuffix: '位 / 30天', monthSuffix: '/ 月',
    benefits: ['拟按30天分批提供', '适用于1个Instagram账号', '无需提供账号密码', '正在调研流失补充选项'], planCta: '我对{plan}感兴趣',
    pricingNote: '所有价格均以美元计，为拟定方案。价格、数量及税费将在正式上线时确认。目前不接受订单或付款。', howTitle: ['我们设想的方式，', '很简单。'], plannedLabel: '正式上线后的拟定使用方式',
    steps: [['选择你的节奏', '根据账号需求，', '选择每月数量。'], ['分散在30天里', '不集中在一次，', '而是贯穿整个月。'], ['继续下个月', '按需要的时间，', '延续订阅节奏。']],
    faqTitle: ['在开始之前，', '先说清楚。'],
    faq: [
      ['登记后会立即开始吗？', '尚未上线。我们目前只调研大家对方案的兴趣，不提供粉丝、不收费，也不会开启自动续费。意向登记不收集联系方式，并非邮箱候补名单。'],
      ['这些粉丝来自自然增长吗？', '我们正在评估由第三方提供粉丝的订阅模式。分30天提供并不意味着自然流入，无法保证真实兴趣、互动、收入、留存或账号安全。该模式可能违反平台条款并导致账号受限，因此是否上线仍在评估中。'],
      ['粉丝流失后会补充吗？', '粉丝可能流失，我们不保证维持数量。本次调查会了解大家对补充选项的需求。只有在验证供应质量和成本后，才会确定补充范围、期限与条件。'],
      ['支持其他社交平台吗？', '当前拟定价格和数量适用于Instagram。登记时可选择YouTube或TikTok，供我们评估未来需求。这并不代表承诺支持或确定价格。']
    ],
    closing: ['下一个月，', '让影响力更有节奏。'], closingCta: '留下我的方案意向', closingNote: '约10秒 · 无需邮箱 · 无需付款',
    disclosure: 'INFLORY正在调研第三方粉丝月度订阅模式。分批提供不等于自然增长，不保证互动、收入、留存数量、账号安全或符合平台条款。',
    privacyLink: '隐私与统计说明', settings: '统计设置', noScript: '您可以浏览所有方案。登记意向需要启用JavaScript。', close: '关闭',
    formTitle: ['你期待怎样的', '下一个月？'], formIntro: ['告诉我们你感兴趣的方案。', '这是一项不收集联系方式的上线前调查。'], planLegend: '感兴趣的方案', formPrice: '每月${price} · {followers}位', platformLabel: '感兴趣的平台', platformOptions: ['Instagram', 'YouTube（未来需求调研）', 'TikTok（未来需求调研）'],
    refill: '我希望有粉丝流失补充选项。', consent: '我同意通过Google Analytics收集所选方案、平台及使用统计。', more: '详情', formSubmit: '登记对此方案的兴趣',
    formFine: '方案拟采用第三方供应，不保证自然流入或留存。本次登记并非购买，也不收集候补联系信息。',
    successTitle: ['感谢你', '留下意向。'], successDetail: '{plan} · {platform}', successText: ['你的选择将帮助我们评估服务构想。', '没有付款或订阅被启动。'], successButton: '返回方案',
    privacyTitle: '隐私与统计说明', operator: '运营方：The Mercenary · 服务构想：INFLORY',
    privacy: [
      ['我们使用哪些信息？', '我们不收集邮箱、电话号码、社交账号名或密码。仅在同意后，通过Google Analytics 4处理页面浏览、点击、所选方案、平台、补充意愿、设备及来源等统计信息。'],
      ['为什么使用？', '我们比较浏览、方案选择与意向登记的比例，以了解需求。意向登记不保存联系方式，也不会发送上线通知。'],
      ['选择与保留', '未经同意不会启动统计。你可随时通过页脚的统计设置撤回同意。选择保存在当前浏览器中。统计Cookie和事件的保留期限由所连接GA4属性的设置和Google政策决定。撤回后停止发送，并尝试删除本页的统计Cookie。']
    ], googlePrivacy: 'Google 隐私权政策', confirm: '确认', consentTitle: '一起构想下一个月。', consentText: '可以收集页面使用统计吗？', deny: '暂不允许', allow: '允许统计',
    ui: { pending: '意向登记尚未开放，请稍后再来。', sending: '正在发送意向…', error: '未能完成连接，请稍后重试或检查内容拦截设置。', duplicate: '你已在本次访问中表达过意向，谢谢。', consentRequired: '发送意向前，请同意统计收集。', selectPlan: '请选择一个方案。', noAnalytics: '统计尚未连接。', invalid: '请检查所选内容。' }
  }
};
