// Consent is separate from registration. Do not pre-check launch notifications.
export const waitlist = {
  en: {
    title:'Join the INFLORY waitlist', heading:['Your next month,','starts here.'], intro:'Tell us what you have in mind. This is a pre-launch application, not a purchase.',
    back:'Back to plans', required:'Required', optional:'Optional', name:'Name', nameHint:'Your name or preferred name, up to 80 characters.', country:'Country / region of residence', countryPlaceholder:'Select your country / region', email:'Email address', emailHint:'Used to manage your application. Launch emails are sent only if you opt in below.',
    platforms:'Platforms you are interested in', platformHint:'Choose at least one. Multiple selections are welcome.', platformPlaceholder:'Select platforms', selected:'{count} selected', platformLabels:['Facebook Page','Instagram','YouTube','X','Other'],
    quantity:'How many followers per month?', quantityHint:'Total across your selected platforms. Choose one range.', over:'3,001 or more',
    privacyLabel:'I have read the application data notice and agree to the processing described below.',
    optin:'Email me when INFLORY opens. I agree to receive a service-launch notification from The Mercenary.', optinHint:'Optional and off by default. You can apply without opting in. You can withdraw at any time by emailing themercenary@duck.com; launch emails will also explain how to unsubscribe by reply. No ongoing newsletter consent is requested.',
    noticeTitle:'About your application data', notice:'The Mercenary uses your name, residence country/region, email, selected platforms, monthly range and consent record to manage applications and assess demand. Only opted-in applicants will receive a launch notification. Submissions are processed by FormSubmit and emailed to themercenary@duck.com (including its forwarding mailbox). This can involve processing outside your country. FormSubmit documents a 30-day submission archive. Our application retention limit is 12 months from submission, or earlier upon a deletion request; removal from the operator mailbox is handled by the operator, not automatically by this page. For access, correction, deletion or withdrawal, contact themercenary@duck.com.',
    providerPrivacy:'FormSubmit privacy policy', withdraw:'Withdraw consent / request deletion', submit:'Submit my application', sending:'Opening secure submission…', processing:'You may be taken to FormSubmit for a security check, then returned here. Nothing is charged and no service starts.', noScript:'Please enable JavaScript to validate and submit this form. Your details are not saved in this browser.',
    errors:{name:'Enter a name of 1–80 characters (no angle brackets or control characters).',country:'Select a country / region.',email:'Enter a valid email address, such as name@example.com.',platforms:'Choose at least one platform.',quantity:'Choose one monthly follower range.',privacy:'Please review and agree to the application data notice.',summary:'Complete all required fields before submitting.'},
    thanksTitle:'Thank you for your interest.', thanks:'If you arrived here after completing the submission service’s confirmation, your application has been handed off for email delivery. This page cannot verify delivery to the operator’s inbox. No payment or subscription has started.',thanksOptin:'Launch notifications will be sent only if you opted in. To withdraw consent or ask about delivery, contact themercenary@duck.com.',
    cta:'Join the waitlist',ctaPlan:'Apply with {plan}',ctaNote:'About 1 minute · No payment · Launch emails optional',faq:'This is a pre-launch application. We ask for your name, residence country/region, email, preferred platforms and monthly volume. Launch notifications are optional. We do not deliver followers, take payments or activate subscriptions at this stage.',
    privacyTitle:'Application data & analytics', analyticsNotice:'Application fields are never sent to Google Analytics. Optional landing-page analytics has its own separate consent. The application and return pages do not load Google Analytics.', countPurpose:'Application preferences and optional landing-page usage statistics help us assess demand. An application is not an order, a guarantee of launch or a promise of follower retention.'
  },
  ko: {
    title:'INFLORY 사전신청',heading:['다음 한 달의','가능성을 남겨주세요.'],intro:'원하시는 방향을 알려주세요. 지금은 사전신청이며, 구매나 구독이 시작되지 않습니다.',
    back:'플랜으로 돌아가기',required:'필수',optional:'선택',name:'이름',nameHint:'성함 또는 사용하시는 이름을 80자 이내로 입력해주세요.',country:'거주 국가 / 지역',countryPlaceholder:'거주 국가 / 지역 선택',email:'이메일 주소',emailHint:'신청 관리에 사용합니다. 출시 알림은 아래에서 동의한 경우에만 발송합니다.',
    platforms:'희망 플랫폼',platformHint:'최소 1개 필수 · 여러 개를 선택할 수 있습니다.',platformPlaceholder:'플랫폼 선택하기',selected:'{count}개 선택',platformLabels:['페이스북 페이지','인스타그램','유튜브','X','기타'],
    quantity:'월 희망 팔로워 수',quantityHint:'선택한 플랫폼 전체를 합한 월 수량입니다. 한 가지만 선택해주세요.',over:'3,001명 이상',
    privacyLabel:'아래 신청 정보 처리 안내를 확인하고, 안내된 정보 처리에 동의합니다.',
    optin:'The Mercenary가 보내는 INFLORY 서비스 오픈 알림 이메일 수신에 동의합니다.',optinHint:'선택 항목이며 기본값은 미동의입니다. 동의하지 않아도 신청할 수 있습니다. 언제든 themercenary@duck.com으로 동의를 철회할 수 있으며, 발송되는 알림 이메일에도 회신을 통한 수신거부 방법을 안내합니다. 지속적인 뉴스레터 수신 동의는 받지 않습니다.',
    noticeTitle:'신청 정보 처리 안내',notice:'The Mercenary는 이름, 거주 국가·지역, 이메일, 희망 플랫폼, 월 희망 수량 및 동의 기록을 사전신청 관리와 수요 파악에 사용합니다. 오픈 알림은 별도로 수신에 동의한 분에게만 발송합니다. 신청 정보는 FormSubmit을 통해 처리되어 themercenary@duck.com 및 연결된 전달 수신함으로 발송되며, 거주 국가 외에서 처리될 수 있습니다. FormSubmit은 신청 내역을 30일간 보관한다고 안내합니다. 운영자의 신청 정보 보관기준은 신청일로부터 최대 12개월 또는 그 이전 삭제 요청 시까지이며, 운영자 수신함에서의 삭제는 운영자가 처리하고 이 페이지에서 자동 수행하지 않습니다. 열람·수정·삭제·동의 철회 문의: themercenary@duck.com.',
    providerPrivacy:'FormSubmit 개인정보 처리방침',withdraw:'동의 철회 / 삭제 요청',submit:'사전신청하기',sending:'보안 전송 화면으로 이동 중…',processing:'전송 시 FormSubmit의 보안 확인 화면을 거친 뒤 이 사이트로 돌아올 수 있습니다. 결제나 서비스 이용은 시작되지 않습니다.',noScript:'필수값 확인과 신청을 위해 JavaScript를 켜주세요. 입력 정보는 브라우저에 따로 저장하지 않습니다.',
    errors:{name:'이름을 1~80자로 입력해주세요. 꺾쇠 괄호와 제어문자는 사용할 수 없습니다.',country:'거주 국가 / 지역을 선택해주세요.',email:'name@example.com 형태의 유효한 이메일 주소를 입력해주세요.',platforms:'희망 플랫폼을 최소 1개 선택해주세요.',quantity:'월 희망 팔로워 수를 한 가지 선택해주세요.',privacy:'신청 정보 처리 안내를 확인하고 동의해주세요.',summary:'필수 항목을 모두 입력하면 신청할 수 있습니다.'},
    thanksTitle:'관심을 남겨주셔서 감사합니다.',thanks:'전송 서비스의 확인 절차를 마치고 이 페이지로 돌아오셨다면 신청 정보가 이메일 발송 절차로 전달되었습니다. 이 페이지에서 운영자 수신함 도착 여부까지 확인할 수는 없습니다. 결제나 구독은 시작되지 않았습니다.',thanksOptin:'오픈 알림은 수신에 동의한 경우에만 발송합니다. 동의 철회 또는 도착 확인 문의: themercenary@duck.com.',
    cta:'사전신청하기',ctaPlan:'{plan} 사전신청',ctaNote:'약 1분 · 결제 없음 · 오픈 알림 수신은 선택',faq:'출시 전 사전신청 단계입니다. 이름, 거주 국가·지역, 이메일, 희망 플랫폼과 월 수량을 받으며, 오픈 알림 이메일 수신은 선택입니다. 지금은 실제 팔로워 제공·결제·자동 갱신을 진행하지 않습니다.',privacyTitle:'신청 정보 및 이용 통계 안내',analyticsNotice:'신청서의 개인정보는 Google Analytics에 전송하지 않습니다. 랜딩페이지 이용 통계는 별도의 선택 동의로만 수집하며, 신청 및 전송 후 안내 페이지에서는 Google Analytics를 불러오지 않습니다.',countPurpose:'신청 선호도와 별도 동의한 랜딩페이지 이용 통계를 통해 수요를 확인합니다. 신청은 주문이나 출시 확정, 팔로워 유지 보장을 뜻하지 않습니다.'
  },
  ja: {
    title:'INFLORY 事前申し込み',heading:['次のひと月の、','希望を聞かせてください。'],intro:'ご希望を教えてください。公開前の申し込みであり、購入や契約は始まりません。',back:'プランに戻る',required:'必須',optional:'任意',name:'お名前',nameHint:'お名前または普段お使いの名前を80文字以内で入力してください。',country:'お住まいの国・地域',countryPlaceholder:'国・地域を選択',email:'メールアドレス',emailHint:'申し込み管理に使用します。公開通知は下記で同意された場合のみ送信します。',
    platforms:'希望するプラットフォーム',platformHint:'1つ以上必須。複数選択できます。',platformPlaceholder:'プラットフォームを選択',selected:'{count}件選択',platformLabels:['Facebookページ','Instagram','YouTube','X','その他'],quantity:'毎月希望するフォロワー数',quantityHint:'選択したプラットフォーム全体の月間合計です。1つ選択してください。',over:'3,001人以上',privacyLabel:'下記の申し込み情報の取り扱いを確認し、記載された処理に同意します。',
    optin:'The MercenaryからINFLORYのサービス公開通知メールを受け取ることに同意します。',optinHint:'任意で、初期状態は未選択です。同意しなくても申し込めます。themercenary@duck.comへのメールでいつでも撤回できます。通知メールにも返信による配信停止方法を記載します。継続的なニュースレターへの同意ではありません。',
    noticeTitle:'申し込み情報の取り扱い',notice:'The Mercenaryは名前、居住国・地域、メール、希望プラットフォーム、月間人数、同意記録を申し込み管理と需要調査に使用します。公開通知は別途同意した方にのみ送信します。情報はFormSubmitで処理され、themercenary@duck.comとその転送先に届きます。居住国外で処理される場合があります。FormSubmitは30日間の送信記録保管を案内しています。運営側の保管基準は申し込みから最長12か月、またはそれ以前の削除依頼までです。受信箱からの削除は運営者が対応し、このページによる自動削除ではありません。開示・訂正・削除・撤回の連絡先：themercenary@duck.com。',providerPrivacy:'FormSubmit プライバシーポリシー',withdraw:'同意撤回・削除依頼',submit:'事前申し込みを送信',sending:'安全確認の画面へ移動中…',processing:'FormSubmitの安全確認画面を経由して、このサイトに戻る場合があります。決済やサービスは開始されません。',noScript:'入力確認と送信にはJavaScriptを有効にしてください。入力情報をブラウザに別途保存しません。',
    errors:{name:'1〜80文字の名前を入力してください。山括弧・制御文字は使えません。',country:'居住国・地域を選択してください。',email:'name@example.comのような有効なメールを入力してください。',platforms:'プラットフォームを1つ以上選択してください。',quantity:'月間フォロワー数を1つ選択してください。',privacy:'情報の取り扱いを確認し、同意してください。',summary:'必須項目をすべて入力すると送信できます。'},thanksTitle:'お申し込みに感謝いたします。',thanks:'送信サービスの確認を終えてこのページに戻った場合、申し込みはメール送信処理に引き渡されました。このページでは運営者の受信箱への到着まで確認できません。決済・契約は開始されていません。',thanksOptin:'公開通知は同意された場合のみ送信します。撤回や到着確認：themercenary@duck.com。',cta:'事前申し込み',ctaPlan:'{plan}で申し込む',ctaNote:'約1分 · 決済なし · 公開通知は任意',faq:'公開前の申し込みです。名前、居住国・地域、メール、希望プラットフォーム、月間人数を伺います。公開通知メールは任意です。現在、フォロワー提供・決済・自動更新は行いません。',privacyTitle:'申し込み情報・利用統計',analyticsNotice:'申し込みの個人情報をGoogle Analyticsへ送りません。ランディングページの統計には別の任意同意を使い、申し込み・送信後の案内ページではGoogle Analyticsを読み込みません。',countPurpose:'希望内容と別途同意された利用統計から需要を確認します。申し込みは注文、公開確約、フォロワー維持保証ではありません。'
  },
  'zh-hans': {
    title:'INFLORY 上线前申请',heading:['下一个月，','说说你的期待。'],intro:'告诉我们你的需求。这是上线前申请，不会开始购买或订阅。',back:'返回方案',required:'必填',optional:'选填',name:'姓名',nameHint:'请输入姓名或惯用称呼，不超过80个字符。',country:'居住国家 / 地区',countryPlaceholder:'选择国家 / 地区',email:'电子邮箱',emailHint:'用于管理申请。仅在下方同意后才会发送上线通知。',platforms:'希望使用的平台',platformHint:'至少选择1项，可以多选。',platformPlaceholder:'选择平台',selected:'已选{count}项',platformLabels:['Facebook主页','Instagram','YouTube','X','其他'],quantity:'每月期望的粉丝数量',quantityHint:'按所选平台的月度合计计算，请选择一项。',over:'3,001位及以上',privacyLabel:'我已阅读下方申请信息处理说明，并同意其中所述的处理。',
    optin:'我同意接收The Mercenary发送的INFLORY服务上线通知邮件。',optinHint:'此项可选，默认不勾选。不同意也可以申请。随时可发邮件至themercenary@duck.com撤回同意；通知邮件也将说明通过回复退订的方法。本次不征求持续订阅新闻邮件的同意。',noticeTitle:'申请信息处理说明',notice:'The Mercenary使用姓名、居住国家或地区、邮箱、所选平台、月度数量及同意记录来管理申请和了解需求。上线通知仅发给另行同意的申请者。信息经FormSubmit处理，发送至themercenary@duck.com及其转发邮箱，可能在居住国以外处理。FormSubmit说明其提交档案保留30天。运营方保留申请信息的期限为申请后最长12个月，或在此之前收到删除请求时为止。邮箱中的删除由运营方处理，并非此页面自动执行。如需访问、更正、删除或撤回同意，请联系themercenary@duck.com。',providerPrivacy:'FormSubmit隐私政策',withdraw:'撤回同意 / 请求删除',submit:'提交上线前申请',sending:'正在前往安全验证页面…',processing:'提交时可能需要通过FormSubmit安全验证，再返回本站。不会扣款或开始服务。',noScript:'请启用JavaScript以检查必填项并提交。输入信息不会另行保存在浏览器中。',
    errors:{name:'请输入1至80个字符的姓名，不含尖括号或控制字符。',country:'请选择居住国家 / 地区。',email:'请输入有效邮箱，例如name@example.com。',platforms:'请至少选择一个平台。',quantity:'请选择一个月度粉丝数量范围。',privacy:'请阅读并同意申请信息处理说明。',summary:'填写所有必填项后即可提交。'},thanksTitle:'感谢你留下申请。',thanks:'如果完成提交服务的确认后返回此页，申请已转交邮件发送流程。此页面无法确认邮件是否到达运营方收件箱。没有开始付款或订阅。',thanksOptin:'仅在同意后发送上线通知。撤回同意或确认送达：themercenary@duck.com。',cta:'上线前申请',ctaPlan:'申请{plan}方案',ctaNote:'约1分钟 · 无需付款 · 上线通知可选',faq:'这是上线前申请。我们收集姓名、居住国家或地区、邮箱、希望使用的平台和月度数量。上线通知邮件为可选项。目前不提供粉丝、不收费，也不会启动自动续费。',privacyTitle:'申请信息与使用统计',analyticsNotice:'申请中的个人信息不会发送到Google Analytics。落地页统计另行征求自愿同意，申请及提交后说明页不加载Google Analytics。',countPurpose:'申请偏好和另行同意的落地页统计用于了解需求。申请并非订单、上线承诺或粉丝留存保证。'
  }
};
export const platformIds=['facebook_page','instagram','youtube','x','other'];
export const volumes=['10-50','51-100','101-300','301-500','501-1000','1001-3000','3001+'];
export const consentVersion='waitlist-2026-09-19-v1';
