import { waitlist, platformIds, volumes, consentVersion } from './waitlist-content.mjs';
import { countries } from './countries.mjs';
import { locales } from './content.mjs';

const e = value => String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const json = value => JSON.stringify(value).replaceAll('<','\\u003c');
const labels={en:'English',ko:'한국어',ja:'日本語','zh-hans':'简体中文'};
export function waitlistPage(locale, thanks=false) {
 const t=waitlist[locale], lang=locales[locale].lang;
 const route=thanks?'thanks':'apply';
 const canonical=`https://themercenary.org/inflory/${locale}/${route}/`;
 const display=new Intl.DisplayNames([lang],{type:'region'});
 const countryOptions=countries.map(code=>({code,label:display.of(code)})).sort((a,b)=>a.label.localeCompare(b.label,lang));
 const required=`<span class="required-tag">${t.required}</span>`;
 const error=(id)=>`<p class="field-error" id="${id}-error" aria-live="polite"></p>`;
 const rangeLabel=(v)=>v==='3001+'?t.over:v.split('-').map(n=>Number(n).toLocaleString(lang)).join('–');
 return `<!doctype html><html lang="${lang}" data-locale="${locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#123f33"><meta name="referrer" content="strict-origin-when-cross-origin"><meta name="robots" content="noindex,follow"><title>${e(thanks?t.thanksTitle:t.title)} — INFLORY</title><meta name="description" content="${e(t.intro)}"><link rel="canonical" href="${canonical}">${Object.entries(locales).map(([key,c])=>`<link rel="alternate" hreflang="${c.lang}" href="https://themercenary.org/inflory/${key}/${route}/">`).join('')}<link rel="icon" href="/inflory/assets/mark.svg"><link rel="stylesheet" href="/inflory/style.css"><link rel="stylesheet" href="/inflory/waitlist.css"><script type="application/json" id="form-copy">${json(t)}</script><script type="module" src="/inflory/waitlist.js"></script></head><body>
 <a class="skip-link" href="#main">${e(locales[locale].skip)}</a><header class="site-header wrap"><a class="brand" href="/inflory/${locale}/">inflory.</a><label class="language-control"><span class="sr-only">${e(locales[locale].language)}</span><select id="application-language">${Object.entries(labels).map(([code,label])=>`<option value="${code}" ${code===locale?'selected':''}>${label}</option>`).join('')}</select></label></header>
 <main id="main" class="application-wrap"><a class="back-link" href="/inflory/${locale}/#plans">← ${e(t.back)}</a>${thanks?`<section class="receipt"><p class="eyebrow">THANK YOU FOR YOUR INTEREST</p><h1>${e(t.thanksTitle)}</h1><p>${e(t.thanks)}</p><p>${e(t.thanksOptin)}</p><a class="button button-green" href="/inflory/${locale}/">${e(t.back)} ↗</a></section>`:`<div class="application-heading"><p class="eyebrow">THE NEXT MONTH STARTS WITH YOU</p><h1>${t.heading.map(e).join('<br>')}</h1><p>${e(t.intro)}</p></div>
 <form id="application-form" action="https://formsubmit.co/themercenary@duck.com" method="POST" accept-charset="UTF-8" autocomplete="on">
 <input type="hidden" name="_subject" value="[INFLORY] Pre-launch application / ${locale}"><input type="hidden" name="_template" value="table"><input type="hidden" name="_next" value="https://themercenary.org/inflory/${locale}/thanks/"><input type="hidden" name="_url" value="https://themercenary.org/inflory/${locale}/apply/">
 <input type="hidden" name="form_version" value="${consentVersion}"><input type="hidden" name="language" value="${locale}"><input type="hidden" name="submitted_at_utc"><input type="hidden" name="retention_review_due"><input type="hidden" name="launch_email_consent" value="no"><input type="hidden" name="launch_consent_text" value="${e(t.optin)}"><input type="hidden" name="privacy_notice_text" value="${e(t.notice)}"><input type="hidden" name="selected_plan" value="unspecified"><input type="hidden" name="residence_country_label"><input type="text" name="_honey" class="bot-field" tabindex="-1" autocomplete="off" aria-hidden="true">
 <div class="field"><label for="app-name">${e(t.name)} ${required}</label><input id="app-name" name="name" autocomplete="name" maxlength="80" required aria-describedby="name-hint name-error"><p class="field-hint" id="name-hint">${e(t.nameHint)}</p>${error('name')}</div>
 <div class="field"><label for="app-country">${e(t.country)} ${required}</label><select id="app-country" name="residence_country" autocomplete="country" required aria-describedby="country-error"><option value="">${e(t.countryPlaceholder)}</option>${countryOptions.map(c=>`<option value="${c.code}">${e(c.label)}</option>`).join('')}</select>${error('country')}</div>
 <div class="field"><label for="app-email">${e(t.email)} ${required}</label><input id="app-email" name="email" type="email" autocomplete="email" inputmode="email" spellcheck="false" autocapitalize="none" maxlength="254" required aria-describedby="email-hint email-error"><p class="field-hint" id="email-hint">${e(t.emailHint)}</p>${error('email')}</div>
 <div class="field"><p class="field-label" id="platform-label">${e(t.platforms)} ${required}</p><p class="field-hint" id="platform-hint">${e(t.platformHint)}</p><details id="platform-picker" class="platform-picker"><summary aria-describedby="platform-hint platforms-error"><span id="platform-count">${e(t.platformPlaceholder)}</span><span aria-hidden="true">⌄</span></summary><fieldset aria-labelledby="platform-label">${platformIds.map((id,i)=>`<label class="platform-option"><input type="checkbox" name="platform_${id}" value="yes" data-platform="${id}"><span>${e(t.platformLabels[i])}</span></label>`).join('')}</fieldset></details>${error('platforms')}</div>
 <fieldset class="field volume-options"><legend>${e(t.quantity)} ${required}</legend><p class="field-hint" id="quantity-hint">${e(t.quantityHint)}</p><div class="volume-grid">${volumes.map(v=>`<label><input type="radio" name="monthly_followers" value="${v}" required aria-describedby="quantity-hint quantity-error"><span>${e(rangeLabel(v))}</span></label>`).join('')}</div>${error('quantity')}</fieldset>
 <section class="application-privacy" aria-labelledby="data-heading"><details><summary id="data-heading">${e(t.noticeTitle)} <span aria-hidden="true">+</span></summary><p>${e(t.notice)}</p><a href="https://formsubmit.co/privacy.pdf" target="_blank" rel="noopener noreferrer">${e(t.providerPrivacy)} ↗</a></details><label class="checkbox-row"><input type="checkbox" name="privacy_acknowledged" id="privacy-agreed" value="yes" required aria-describedby="privacy-error"><span>${required} ${e(t.privacyLabel)}</span></label>${error('privacy')}
 <label class="checkbox-row launch-option"><input type="checkbox" id="launch-consent"><span><span class="optional-tag">${e(t.optional)}</span> ${e(t.optin)}</span></label><p class="field-hint">${e(t.optinHint)}</p></section>
 <p id="application-status" role="status" aria-live="polite">${e(t.errors.summary)}</p><button id="application-submit" class="button button-green" type="submit" disabled>${e(t.submit)} <span aria-hidden="true">↗</span></button><p class="submission-note">${e(t.processing)}</p><noscript><p class="field-error">${e(t.noScript)}</p></noscript></form>`}
 <p class="application-contact"><a href="mailto:themercenary@duck.com?subject=INFLORY%20-%20unsubscribe%20or%20delete%20my%20application">${e(t.withdraw)} ↗</a></p></main><footer class="site-footer wrap"><a href="https://themercenary.org/">© 2026 The Mercenary</a><nav class="form-languages" aria-label="${e(locales[locale].language)}">${Object.entries(labels).map(([key,label])=>`<a lang="${locales[key].lang}" href="/inflory/${key}/${route}/">${label}</a>`).join('')}</nav></footer></body></html>`;
}
